version: '3.8'

services:
  postgres:
    container_name: roommonitor_db
    image: postgres:alpine
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - ./local_init:/docker-entrypoint-initdb.d

  nestjs:
    container_name: roommonitor_api
    image: 'node:latest'
    working_dir: /usr/api
    command: bash -c "npm i && npm run start:debug"
    env_file:
      - .env  
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/api

networks:
  default:
    name: roommonitor-network